resource_labels    = { "provider" : "jx" }
jx_git_url         = "https://github.com/collibra/cicd_jx3_dgc_cluster_gcp_dev"
gcp_project        = "cicd-jenkinsx-prd"
cluster_name       = "cicd-jenkinsx-dgc-dev"
jx_bot_username    = "cicd-jenkinsx-1"
node_machine_type  = "n1-standard-4"
cluster_location   = "europe-west1-b"
gsm                = true
cluster_network    = "cicd-network"
cluster_subnetwork = "dgc-dev-cicd-subnet"
bucket_location    = "EU"
max_node_count     = 10